#! /bin/bash

bash run_cc2vec.sh phaser part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh bootstrap part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh elasticsearch part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh php-src part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh flink part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh yuzu part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh swift part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh cpython part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh salt part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh TDengine part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh shardingsphere part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh pandas part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh moment part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh presto part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh transformers part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh mpv part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh openssl part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh keycloak part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh kafka part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh scipy part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh scikit-learn part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh Ghost part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh tensorflow part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh lede part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh netty part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh netdata part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh numpy part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh jenkins part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh emscripten part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh skywalking part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh mongoose part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh redis part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh jumpserver part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh eslint part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh tesseract part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh codemirror5 part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh obs-studio part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh scrapy part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh uppy part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh libuv part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh preact part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh carbon-lang part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh grpc part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh yolov5 part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh electron part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh caffe part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50
bash run_cc2vec.sh protobuf part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/truncated_median_date_tan_dataset 50

bash run_cc2vec.sh c part_1_part_4 part_5 /data/gpfs/projects/punim1928/RISE/JITDP/crawling/cross-lang 1